### ISSUE TITLE
Question about JOIN queries

### ISSUE THREAD

**Issue by lumaxis** [chrisdickinson/ormnomnom#184]
For the [JOINs example from the docs](https://github.com/chrisdickinson/ormnomnom/blob/main/docs/making-queries.md#using-joins), if I want to have ormnomnom generate a JOIN query where only the _other_ model has a foreign key that points to my model, is that at all possible?

So sticking with the example, I want to basically be able to do:

```js
AuthorObjects.filter({
  'book.isNull': false
})
```

With everything I've been trying so far, I eventually run into errors where it complains about `authors.book_id` not being a valid column (which is true) but the SQL query I'm ultimately trying to get to is something like:

```sql
SELECT * FROM authors
LEFT JOIN books
ON author.id = books.author_id
```

Is that at all possible? I'm fine with even a hacky way 🙂 Thanks!

**Comment by chrisdickinson** [comment]
Sorry for the delayed response! Yes! That is possible – it's a "reverse relation":

```
AuthorObjects.filter({
  'books.id:isNull': false // note the plural! reverse relations are installed on the referring model under the referred model's table name
})
```

**Comment by lumaxis** [comment]
Thanks! I managed to make this work similarly to this but I think I needed a version of this on the model:

```js
const AuthorObjects = orm(Author, {
  book: orm.fk(Book, { nullable: true, column: 'id' })
})
```

Without this, ormnomnom seemed to be looking for a column called `book_id` on the `authors` table which doesn't exist.
Eventually though, I ended up going a completely separate route and used a sub-select which worked much better for my slightly more complex constraint:

```js
AuthorObjects.filter({
  'book.id:raw' (column) {
    return `${column} IN (SELECT id FROM books WHERE author_id = books.id AND deleted IS NULL AND read = false)`
  }
})
