### ISSUE TITLE
Difference between .get() versus .filter().distinct() ?

### ISSUE THREAD

**Issue by jaredpalmer** [chrisdickinson/ormnomnom#19]

**Comment by jaredpalmer** [comment]
This library rocks btw. Couple of questions: 

- Why are you using setters and getters here? https://github.com/npm/oauth2-server-pg/blob/master/lib/token.js#L28 . Caching?

- I have a table Memberships with compound primary keys (user_id, account_id)? My Joi schema looks like this:
```
Membership.objects = orm(Membership, {
  role: orm.joi.string().required(),
  state: orm.joi.string().default('pending'),
  created: orm.joi.date().default(() => {
    return (new Date()).toISOString()
  }, 'date'),
  updated: orm.joi.date().default(() => {
    return (new Date()).toISOString()
  }, 'date'),
  user: orm.fk(User),
  account: orm.fk(Account)
})
```
Like github's `/orgs/:org/memberships` endpoint, I want to expand both the user and account fields in my response. After some work, i figured out that i could force ormnomnom to expand both with one line: `Memberships.filter({ 'account.id': xxx, 'user.id:isNull' false })`. Is this correct/performant?

- On another project I have Orders _has_many_ LineItems. So order_id is a fk on line_items table. I want to filter Orders and get each of their Line_Items so my end output can look like:

```

[
Order {
  id,
  total_amount,
  status,
  line_items: [{
     id,
     price,
     quantity
  },  {
     id,
     price,
     quantity
  }]
},
Order {
  id,
  total_amount,
  status,
  line_items: [{
     id,
     price,
     quantity
  },  {
     id,
     price,
     quantity
  }]
},
...
]
```

I can't use `LineItem` directly in my `Order` class declaration because of a circular dependency. So my code looks like this:

```
const orders = await Order.objects.filter({ 'payment_status:isNull': true }).slice(0,2)
const ordersWithDetails = await Promise.all(orders.map(o => getOrderDetails(o)))

async function getOrderDetails (order) {
  return await LineItem.objects.filter({'order_id': order.id}).then(l => transformOrder(order, l))
}

function transformOrder(order, line_items) {
  return Object.assign({}, order, {
    line_items,
    total_amount: line_items.reduce((a, b) => (a + (b.price * b.quantity)), 0)
  })
}
```

Is their a better way of doing this? How have you solved this kind of thing in the past?

**Comment by chrisdickinson** [comment]
Sorry for being immensely late to the party on this one, but!

Re: your first question: whenever I need to materialize a join, I'll do as you've done and add a `{'name_of_join.id:isNull': false}` to the queryset. This is a bit of a hack though, I should add a `.related()` function to do this!

Re: the second: This will end up being an O(N+1) query which can be really pokey when N gets large: you might consider using `:in` to run this in two queries:

```
const orders = await Order.objects.filter({'payment_status:isNull': true})
const orderIds = orders.reduce((acc, xs) => {
  acc.set(xs.id, xs)
  return acc
}, new Map())

const lineItems = (
  !orderIds.length
  ? []
  : await LineItem.objects.filter({
    'order_id:in' Array.from(orderIds.keys())
  })
)

lineItems.forEach(item => {
  const order = orderIds.get(item.order_id)
  order.line_items = order.line_items || []
  order.line_items.push(item)
})
```

**Comment by jaredpalmer** [comment]
@chrisdickinson Thanks for the response. I like the `:in` technique. 

FWIW Thank you for this lib.`ormnomnom` has been rock solid in a payments system I built that's so far processed over $750k in past 6 months. It's 10x better than sequelize/bookshelf/knex stuff.
